### ISSUE TITLE
Syntax Error in ChatModel.swift

### ISSUE THREAD

**Issue by arman-hk** [alexrozanski/LlamaChat#28]
Hey @alexrozanski, at line 73 of ChatModel.swift, you have this:
```swift
guard let lastChatContext else {
        canClearContext = false
        return
      }
```
It seems like a condition is missing:
```swift
      guard let _ = lastChatContext else {
        canClearContext = false
        return
      }
``` 
Shouldn't it look something like the above?

**Comment by alexrozanski** [comment]
@arman-hk this uses the `if let` shorthand introduced in Swift 5.7: https://github.com/apple/swift-evolution/blob/main/proposals/0345-if-let-shorthand.md — functionally it's equivalent to

```swift
guard let lastChatContext = lastChatContext else {
  canClearContext = false
  return
}
```

as we're using the bound non-optional value of `lastChatContext` on line 77.

tbh this would be better written using Combine rather than in the `didSet {}`, I've been tweaking some of these as I've been going back through the codebase as well.

**Comment by arman-hk** [comment]
@alexrozanski, Thank you for clarifying the use of the shortened syntax; I wasn't aware of this new feature. looking forward to seeing the codebase improvements!
